using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using YoutubeExplode;
using YoutubeExplode.Videos;
using YoutubeExplode.Videos.ClosedCaptions;

record Input(string url);

record Options(
    string? Url,
    string Language,
    bool MetadataOnly,
    bool Compact,
    bool ShowHelp,
    bool ShowVersion);

class Output
{
    public string url { get; set; } = "";
    public string title { get; set; } = "";
    public string description { get; set; } = "";
    public string transcriptRaw { get; set; } = "";
    public string transcript { get; set; } = "";
}

static class Program
{
    private const string Usage = """
        ytx extracts YouTube video metadata and captions as JSON.

        Usage:
          ytx [options] <URL_OR_VIDEO_ID>
          echo '{"url":"URL_OR_VIDEO_ID"}' | ytx [options]

        Arguments:
          URL_OR_VIDEO_ID           A YouTube URL or video ID.

        Options:
          -u, --url <value>         Specify the YouTube URL or video ID explicitly.
          -l, --language <value>    Prefer captions matching a language name or code
                                    (default: English).
              --metadata-only       Skip caption retrieval and return metadata only.
          -c, --compact             Write compact JSON instead of indented JSON.
          -h, -?, --help            Show help and exit.
          -v, --version             Show version and exit.

        Output:
          JSON is written to stdout. Diagnostics are written to stderr.

        Exit codes:
          0  Success
          1  Video retrieval or another runtime error
          2  Invalid command-line usage or input
        """;

    static async Task<int> Main(string[] args)
    {
        var (options, error) = ParseOptions(args);
        if (error != null)
        {
            Console.Error.WriteLine($"Error: {error}");
            Console.Error.WriteLine("Try 'ytx --help' for more information.");
            return 2;
        }

        if (options!.ShowHelp)
        {
            Console.WriteLine(Usage);
            return 0;
        }

        if (options.ShowVersion)
        {
            Console.WriteLine($"ytx {GetVersion()}");
            return 0;
        }

        string? url = options.Url;
        if (url == null && Console.IsInputRedirected)
        {
            var stdin = await Console.In.ReadToEndAsync();
            if (!string.IsNullOrWhiteSpace(stdin))
            {
                try
                {
                    var input = JsonSerializer.Deserialize<Input>(stdin.Trim(),
                        new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                    url = input?.url;
                }
                catch (JsonException ex)
                {
                    Console.Error.WriteLine($"Error: Invalid JSON input: {ex.Message}");
                    return 2;
                }
            }
        }

        if (string.IsNullOrWhiteSpace(url))
        {
            Console.Error.WriteLine("Error: A YouTube URL or video ID is required.");
            Console.Error.WriteLine("Try 'ytx --help' for more information.");
            return 2;
        }

        var videoId = VideoId.TryParse(url);
        if (videoId == null)
        {
            Console.Error.WriteLine($"Error: '{url}' is not a valid YouTube URL or video ID.");
            return 2;
        }

        try
        {
            var client = new YoutubeClient();
            var video = await client.Videos.GetAsync(videoId.Value);
            var title = video.Title ?? "";
            var description = video.Description ?? "";

            string transcriptRaw = "";
            string transcriptMd = options.MetadataOnly ? "_Caption retrieval skipped._" : "";

            if (!options.MetadataOnly)
            {
                try
                {
                    var manifest = await client.Videos.ClosedCaptions.GetManifestAsync(video.Id);
                    var track = manifest.Tracks
                        .OrderByDescending(t => LanguageMatches(t.Language.Code, t.Language.Name, options.Language))
                        .ThenByDescending(t => t.IsAutoGenerated)
                        .FirstOrDefault();

                    if (track != null)
                    {
                        var captions = await client.Videos.ClosedCaptions.GetAsync(track);
                        var rawSb = new StringBuilder();
                        var mdSb = new StringBuilder();

                        foreach (var caption in captions.Captions)
                        {
                            var text = NormalizeCaption(caption.Text);
                            if (string.IsNullOrWhiteSpace(text)) continue;

                            if (rawSb.Length > 0) rawSb.Append(' ');
                            rawSb.Append(text);

                            var timestamp = ToHhMmSs(caption.Offset);
                            var link = $"https://www.youtube.com/watch?v={video.Id}&t={(int)caption.Offset.TotalSeconds}s";
                            mdSb.AppendLine($"- [{timestamp}]({link}) {text}");
                        }

                        transcriptRaw = rawSb.ToString().Trim();
                        transcriptMd = mdSb.ToString().TrimEnd();
                    }
                    else
                    {
                        transcriptMd = "_No transcript/captions available for this video._";
                    }
                }
                catch
                {
                    transcriptMd = "_No transcript/captions available or captions retrieval failed._";
                }
            }

            var output = new Output
            {
                url = url,
                title = title,
                description = description,
                transcriptRaw = transcriptRaw,
                transcript = transcriptMd
            };

            var json = JsonSerializer.Serialize(output, new JsonSerializerOptions
            {
                WriteIndented = !options.Compact,
                Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping
            });

            Console.OutputEncoding = Encoding.UTF8;
            Console.WriteLine(json);
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
            return 1;
        }
    }

    internal static (Options? Options, string? Error) ParseOptions(string[] args)
    {
        string? url = null;
        var language = "English";
        var metadataOnly = false;
        var compact = false;
        var showHelp = false;
        var showVersion = false;
        var positionalOnly = false;

        for (var i = 0; i < args.Length; i++)
        {
            var arg = args[i];
            if (!positionalOnly && arg == "--")
            {
                positionalOnly = true;
            }
            else if (!positionalOnly && arg is "-h" or "-?" or "--help")
            {
                showHelp = true;
            }
            else if (!positionalOnly && arg is "-v" or "--version")
            {
                showVersion = true;
            }
            else if (!positionalOnly && arg is "-c" or "--compact")
            {
                compact = true;
            }
            else if (!positionalOnly && arg == "--metadata-only")
            {
                metadataOnly = true;
            }
            else if (!positionalOnly && arg is "-u" or "--url")
            {
                if (++i >= args.Length) return (null, $"Option '{arg}' requires a value.");
                if (url != null) return (null, "The YouTube URL or video ID can only be specified once.");
                url = args[i];
            }
            else if (!positionalOnly && arg is "-l" or "--language")
            {
                if (++i >= args.Length || string.IsNullOrWhiteSpace(args[i]))
                    return (null, $"Option '{arg}' requires a value.");
                language = args[i];
            }
            else if (!positionalOnly && arg.StartsWith('-'))
            {
                return (null, $"Unknown option '{arg}'.");
            }
            else if (url == null)
            {
                url = arg;
            }
            else
            {
                return (null, "Only one YouTube URL or video ID can be specified.");
            }
        }

        if (showHelp && showVersion)
            return (null, "Options '--help' and '--version' cannot be used together.");

        return (new Options(url, language, metadataOnly, compact, showHelp, showVersion), null);
    }

    internal static string GetVersion()
    {
        var informationalVersion = typeof(Program).Assembly
            .GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
        return informationalVersion?.Split('+')[0]
            ?? typeof(Program).Assembly.GetName().Version?.ToString(3)
            ?? "unknown";
    }

    internal static bool LanguageMatches(string code, string name, string preference) =>
        code.Equals(preference, StringComparison.OrdinalIgnoreCase)
        || name.Equals(preference, StringComparison.OrdinalIgnoreCase)
        || name.Contains(preference, StringComparison.OrdinalIgnoreCase);

    internal static string ToHhMmSs(TimeSpan ts)
    {
        int h = (int)ts.TotalHours;
        int m = ts.Minutes;
        int s = ts.Seconds;
        return h > 0 ? $"{h:00}:{m:00}:{s:00}" : $"{m:00}:{s:00}";
    }

    internal static string NormalizeCaption(string text)
    {
        if (string.IsNullOrWhiteSpace(text)) return "";
        text = Regex.Replace(text, @"\s+", " ").Trim();
        return text.Replace("&nbsp;", " ");
    }
}
