using System.Net;
using System.Reflection;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using YoutubeExplode;
using YoutubeExplode.Exceptions;
using YoutubeExplode.Videos;
using YoutubeExplode.Videos.ClosedCaptions;

record Input(string url);

record Options(
    string? Url,
    string Language,
    bool MetadataOnly,
    bool Compact,
    bool ShowHelp,
    bool ShowVersion,
    bool LanguageSpecified = false,
    TimeSpan? Timeout = null,
    string Format = OutputFormat.Json,
    bool Segments = false,
    bool ListLanguages = false,
    Uri? Proxy = null);

static class OutputFormat
{
    public const string Json = "json";
    public const string Markdown = "md";
    public const string Text = "txt";
    public const string Srt = "srt";
    public const string Vtt = "vtt";
    public static readonly string[] All = [Json, Markdown, Text, Srt, Vtt];
}

// Property order is the JSON field order. Nullable fields are written as null, never
// omitted, so every document has the same keys.
class Output
{
    public string url { get; set; } = "";
    public string videoId { get; set; } = "";
    public string title { get; set; } = "";
    public string channel { get; set; } = "";
    public string channelId { get; set; } = "";
    public string? uploadDate { get; set; }
    public int? durationSeconds { get; set; }
    public long? viewCount { get; set; }
    public IReadOnlyList<string> keywords { get; set; } = [];
    public string description { get; set; } = "";
    public string captionStatus { get; set; } = CaptionStatus.Skipped;
    public string? captionLanguage { get; set; }
    public string? captionLanguageName { get; set; }
    public bool? captionIsAutoGenerated { get; set; }
    public string? captionError { get; set; }
    public string transcriptRaw { get; set; } = "";
    public string transcript { get; set; } = "";
    public IReadOnlyList<Segment>? segments { get; set; }
}

// Times are in seconds, rounded to the millisecond.
class Segment
{
    public double start { get; set; }
    public double end { get; set; }
    public string text { get; set; } = "";
}

class LanguagesOutput
{
    public string videoId { get; set; } = "";
    public IReadOnlyList<TrackOutput> tracks { get; set; } = [];
}

class TrackOutput
{
    public string code { get; set; } = "";
    public string name { get; set; } = "";
    public bool isAutoGenerated { get; set; }
}

static class CaptionStatus
{
    public const string Ok = "ok";
    public const string None = "none";
    public const string Skipped = "skipped";
    public const string Blocked = "blocked";
    public const string Error = "error";
}

// Source-generated metadata skips reflection setup at startup and keeps JSON
// working under trimming and NativeAOT, where reflection-based serialization is disabled.
[JsonSerializable(typeof(Input))]
[JsonSerializable(typeof(Output))]
[JsonSerializable(typeof(LanguagesOutput))]
partial class YtxJsonContext : JsonSerializerContext
{
}

static partial class Program
{
    private const string Usage = """
        ytx extracts YouTube video metadata and captions as JSON.

        Usage:
          ytx [options] <URL_OR_VIDEO_ID>
          echo '{"url":"URL_OR_VIDEO_ID"}' | ytx [options]

        Arguments:
          URL_OR_VIDEO_ID           A YouTube URL or video ID. Put '--' before an ID
                                    that starts with '-'. When given, piped input is
                                    not read. Piped JSON uses only its "url" key.

        Options:
          -u, --url <value>         Specify the YouTube URL or video ID explicitly.
          -l, --language <value>    Prefer captions matching a language name or code
                                    (default: English). Falls back to English, then
                                    any track, with a warning on stderr.
              --metadata-only       Skip caption retrieval and return metadata only.
          -f, --format <format>     json (default), or only the transcript as md, txt,
                                    srt or vtt.
              --segments            Add a segments array of {start, end, text} to the
                                    JSON, with times in seconds.
              --list-languages      List the video's caption tracks as JSON and exit.
              --proxy <url>         Send requests through this proxy, such as
                                    http://host:8080 or socks5://host:1080. Without it,
                                    HTTPS_PROXY and the system proxy are used.
              --timeout <seconds>   Give up after this many seconds (default: none).
          -c, --compact             Write compact JSON instead of indented JSON.
          -h, -?, --help            Show help and exit.
          -v, --version             Show the ytx version and exit.

        Output:
          JSON (or the chosen format) is written to stdout. Diagnostics are written
          to stderr.

        Exit codes:
          0  Success, including videos with no captions
          1  Video retrieval or another runtime error
          2  Invalid command-line usage or input
          3  Metadata written, but captions were blocked or failed
          130  Cancelled with Ctrl+C
        """;

    static async Task<int> Main(string[] args)
    {
        var (options, error) = ParseOptions(args);
        if (error != null)
        {
            Console.Error.WriteLine($"Error: {error}");
            Console.Error.WriteLine("Try 'ytx --help' for more information.");
            return 2;
        }

        if (options!.ShowHelp)
        {
            Console.WriteLine(Usage);
            return 0;
        }

        if (options.ShowVersion)
        {
            Console.WriteLine($"ytx {GetVersion()}");
            return 0;
        }

        string? url = options.Url;
        if (url == null && Console.IsInputRedirected)
        {
            var stdin = await Console.In.ReadToEndAsync();
            if (!string.IsNullOrWhiteSpace(stdin))
            {
                try
                {
                    var input = JsonSerializer.Deserialize(stdin.Trim(),
                        new YtxJsonContext(new JsonSerializerOptions { PropertyNameCaseInsensitive = true }).Input);
                    url = input?.url;
                }
                catch (JsonException ex)
                {
                    Console.Error.WriteLine($"Error: Invalid JSON input: {ex.Message}");
                    return 2;
                }
            }
        }

        if (string.IsNullOrWhiteSpace(url))
        {
            Console.Error.WriteLine("Error: A YouTube URL or video ID is required.");
            Console.Error.WriteLine("Try 'ytx --help' for more information.");
            return 2;
        }

        var videoId = VideoId.TryParse(url);
        if (videoId == null)
        {
            Console.Error.WriteLine($"Error: '{url}' is not a valid YouTube URL or video ID.");
            return 2;
        }

        if (options.MetadataOnly && options.LanguageSpecified)
        {
            Console.Error.WriteLine("Warning: --language is ignored with --metadata-only.");
        }

        using var cts = new CancellationTokenSource();
        var interrupted = false;
        Console.CancelKeyPress += (_, e) =>
        {
            // Let the in-flight request unwind so the exit code is ours, not the runtime's.
            e.Cancel = true;
            interrupted = true;
            cts.Cancel();
        };
        if (options.Timeout is { } timeout) cts.CancelAfter(timeout);

        try
        {
            using var http = CreateHttpClient(options.Proxy);
            var client = new YoutubeClient(http);
            Console.OutputEncoding = Encoding.UTF8;

            if (options.ListLanguages)
            {
                var manifest = await client.Videos.ClosedCaptions.GetManifestAsync(videoId.Value, cts.Token);
                using var languagesStdout = Console.OpenStandardOutput();
                WriteJson(languagesStdout, CreateLanguagesOutput(videoId.Value, manifest.Tracks),
                    YtxJsonContextFor(options.Compact).LanguagesOutput);
                return 0;
            }

            var video = await client.Videos.GetAsync(videoId.Value, cts.Token);
            var output = CreateOutput(video);

            if (!options.MetadataOnly)
            {
                var segments = await AddCaptionsAsync(client, video.Id, options.Language, output, cts.Token);
                // Text formats are built from the segments, so keep them for those as well.
                if (options.Segments || options.Format != OutputFormat.Json) output.segments = segments;
            }

            using (var stdout = Console.OpenStandardOutput())
            {
                if (options.Format == OutputFormat.Json)
                {
                    WriteOutput(stdout, output, options.Compact);
                }
                else if (output.captionStatus == CaptionStatus.Ok)
                {
                    var text = FormatTranscript(options.Format, output);
                    stdout.Write(new UTF8Encoding(false).GetBytes(text));
                }
            }

            if (options.Format != OutputFormat.Json && output.captionStatus == CaptionStatus.None)
            {
                Console.Error.WriteLine("Warning: This video has no captions.");
            }

            if (output.captionError != null)
            {
                Console.Error.WriteLine($"Warning: Captions {output.captionStatus}: {output.captionError}");
                return 3;
            }
            return 0;
        }
        catch (OperationCanceledException) when (cts.IsCancellationRequested)
        {
            if (interrupted) return 130;
            Console.Error.WriteLine($"Error: Timed out after {options.Timeout!.Value.TotalSeconds:0.###} seconds.");
            return 1;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
            return 1;
        }
    }

    internal static Output CreateOutput(Video video) => new()
    {
        url = $"https://www.youtube.com/watch?v={video.Id}",
        videoId = video.Id.Value,
        title = video.Title ?? "",
        channel = video.Author.ChannelTitle,
        channelId = video.Author.ChannelId.Value,
        uploadDate = video.UploadDate.ToString("yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture),
        durationSeconds = video.Duration is { } d ? (int)d.TotalSeconds : null,
        viewCount = video.Engagement.ViewCount,
        keywords = video.Keywords,
        description = video.Description ?? "",
    };

    // No handler is passed without a proxy, so HttpClient keeps its default proxy, which
    // reads HTTPS_PROXY, HTTP_PROXY and NO_PROXY and falls back to the system setting.
    internal static HttpClient CreateHttpClient(Uri? proxy) => proxy == null
        ? new HttpClient()
        : new HttpClient(new HttpClientHandler { Proxy = new WebProxy(proxy), UseProxy = true }, disposeHandler: true);

    internal static LanguagesOutput CreateLanguagesOutput(VideoId videoId, IEnumerable<ClosedCaptionTrackInfo> tracks) => new()
    {
        videoId = videoId.Value,
        tracks = tracks
            .Select(t => new TrackOutput { code = t.Language.Code, name = t.Language.Name, isAutoGenerated = t.IsAutoGenerated })
            .ToList(),
    };

    // Returns the normalized segments, or an empty list when there is no transcript.
    private static async Task<IReadOnlyList<Segment>> AddCaptionsAsync(
        YoutubeClient client, VideoId videoId, string language, Output output, CancellationToken cancellationToken)
    {
        try
        {
            var manifest = await client.Videos.ClosedCaptions.GetManifestAsync(videoId, cancellationToken);
            var track = SelectTrack(manifest.Tracks, language);
            if (track == null)
            {
                output.captionStatus = CaptionStatus.None;
                return [];
            }

            if (!LanguageMatches(track.Language.Code, track.Language.Name, language))
            {
                Console.Error.WriteLine(
                    $"Warning: No captions match '{language}'; using {track.Language.Name} ({track.Language.Code}).");
            }

            var captions = await client.Videos.ClosedCaptions.GetAsync(track, cancellationToken);
            (output.transcriptRaw, output.transcript) = BuildTranscript(videoId.Value, captions.Captions);
            output.captionStatus = CaptionStatus.Ok;
            output.captionLanguage = track.Language.Code;
            output.captionLanguageName = track.Language.Name;
            output.captionIsAutoGenerated = track.IsAutoGenerated;
            return BuildSegments(captions.Captions);
        }
        // Only failures of the caption fetch itself are reported in the output. Anything
        // else is a bug and should fail loudly instead of looking like a video without captions.
        // HttpClient's own timeout is a TaskCanceledException too, so tell it apart from ours.
        catch (Exception ex) when (ex is YoutubeExplodeException or HttpRequestException or TaskCanceledException
            && !cancellationToken.IsCancellationRequested)
        {
            output.captionStatus = ClassifyCaptionError(ex);
            output.captionError = ex.Message;
            return [];
        }
    }

    // YouTube blocks by rate limiting, by refusing the request, or by asking the client to
    // prove it is not a bot. Callers can retry later or through another network.
    internal static string ClassifyCaptionError(Exception ex) => ex switch
    {
        RequestLimitExceededException => CaptionStatus.Blocked,
        HttpRequestException { StatusCode: System.Net.HttpStatusCode.Forbidden or System.Net.HttpStatusCode.TooManyRequests }
            => CaptionStatus.Blocked,
        _ when ex.Message.Contains("not a bot", StringComparison.OrdinalIgnoreCase) => CaptionStatus.Blocked,
        _ => CaptionStatus.Error,
    };

    internal static (string Raw, string Markdown) BuildTranscript(string videoId, IEnumerable<ClosedCaption> captions)
    {
        var rawSb = new StringBuilder();
        var mdSb = new StringBuilder();

        foreach (var caption in captions)
        {
            var text = NormalizeCaption(caption.Text);
            if (string.IsNullOrWhiteSpace(text)) continue;

            if (rawSb.Length > 0)
            {
                rawSb.Append(' ');
                mdSb.Append(Environment.NewLine);
            }
            rawSb.Append(text);

            // Appending interpolated strings to a StringBuilder formats in place, with no temporary strings.
            mdSb.Append("- [");
            AppendTimestamp(mdSb, caption.Offset);
            mdSb.Append($"](https://www.youtube.com/watch?v={videoId}&t={(int)caption.Offset.TotalSeconds}s) ");
            mdSb.Append(text);
        }

        return (rawSb.ToString().Trim(), mdSb.ToString().TrimEnd());
    }

    internal static IReadOnlyList<Segment> BuildSegments(IEnumerable<ClosedCaption> captions)
    {
        var segments = new List<Segment>();
        foreach (var caption in captions)
        {
            var text = NormalizeCaption(caption.Text);
            if (string.IsNullOrWhiteSpace(text)) continue;
            segments.Add(new Segment
            {
                start = Math.Round(caption.Offset.TotalSeconds, 3),
                end = Math.Round((caption.Offset + caption.Duration).TotalSeconds, 3),
                text = text,
            });
        }

        return segments;
    }

    internal static string FormatTranscript(string format, Output output)
    {
        var segments = output.segments ?? [];
        var sb = new StringBuilder();
        switch (format)
        {
            case OutputFormat.Markdown:
                return output.transcript + Environment.NewLine;
            case OutputFormat.Text:
                foreach (var s in segments) sb.Append(s.text).Append('\n');
                return sb.ToString();
            case OutputFormat.Srt:
                for (var i = 0; i < segments.Count; i++)
                {
                    sb.Append(i + 1).Append('\n');
                    AppendCueTime(sb, segments[i].start, ',').Append(" --> ");
                    AppendCueTime(sb, segments[i].end, ',').Append('\n');
                    sb.Append(segments[i].text).Append("\n\n");
                }
                return sb.ToString();
            case OutputFormat.Vtt:
                sb.Append("WEBVTT\n\n");
                foreach (var s in segments)
                {
                    AppendCueTime(sb, s.start, '.').Append(" --> ");
                    AppendCueTime(sb, s.end, '.').Append('\n');
                    // A blank line or "-->" would end or break a WebVTT cue.
                    sb.Append(s.text.Replace("-->", "->")).Append("\n\n");
                }
                return sb.ToString();
            default:
                throw new ArgumentOutOfRangeException(nameof(format), format, null);
        }
    }

    // HH:MM:SS,mmm for SRT and HH:MM:SS.mmm for WebVTT. Hours grow past two digits if needed.
    private static StringBuilder AppendCueTime(StringBuilder sb, double seconds, char separator)
    {
        var ms = (long)Math.Round(seconds * 1000);
        return sb.Append($"{ms / 3_600_000:00}:{ms / 60_000 % 60:00}:{ms / 1000 % 60:00}{separator}{ms % 1000:000}");
    }

    private static YtxJsonContext YtxJsonContextFor(bool compact) => new(new JsonSerializerOptions
    {
        WriteIndented = !compact,
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
    });

    // Writes UTF-8 without a BOM and ends with the platform newline, matching Console.WriteLine.
    internal static void WriteOutput(Stream stream, Output output, bool compact) =>
        WriteJson(stream, output, YtxJsonContextFor(compact).Output);

    // Serializing to a string sizes its buffer for the worst-case escape of the whole
    // transcript and then copies it as UTF-16. Writing UTF-8 to the stream avoids both.
    internal static void WriteJson<T>(Stream stream, T value, JsonTypeInfo<T> typeInfo)
    {
        JsonSerializer.Serialize(stream, value, typeInfo);
        stream.Write(Encoding.UTF8.GetBytes(Environment.NewLine));
        stream.Flush();
    }

    internal static (Options? Options, string? Error) ParseOptions(string[] args)
    {
        string? url = null;
        var language = "English";
        var languageSpecified = false;
        TimeSpan? timeout = null;
        var metadataOnly = false;
        var format = OutputFormat.Json;
        var segments = false;
        var listLanguages = false;
        Uri? proxy = null;
        var compact = false;
        var showHelp = false;
        var showVersion = false;
        var positionalOnly = false;

        for (var i = 0; i < args.Length; i++)
        {
            var arg = args[i];
            if (!positionalOnly && arg == "--")
            {
                positionalOnly = true;
            }
            else if (!positionalOnly && arg is "-h" or "-?" or "--help")
            {
                showHelp = true;
            }
            else if (!positionalOnly && arg is "-v" or "--version")
            {
                showVersion = true;
            }
            else if (!positionalOnly && arg is "-c" or "--compact")
            {
                compact = true;
            }
            else if (!positionalOnly && arg == "--metadata-only")
            {
                metadataOnly = true;
            }
            else if (!positionalOnly && arg is "-u" or "--url")
            {
                if (++i >= args.Length) return (null, $"Option '{arg}' requires a value.");
                if (url != null) return (null, "The YouTube URL or video ID can only be specified once.");
                url = args[i];
            }
            else if (!positionalOnly && arg is "-l" or "--language")
            {
                if (++i >= args.Length || string.IsNullOrWhiteSpace(args[i]))
                    return (null, $"Option '{arg}' requires a value.");
                language = args[i];
                languageSpecified = true;
            }
            else if (!positionalOnly && arg is "-f" or "--format")
            {
                if (++i >= args.Length) return (null, $"Option '{arg}' requires a value.");
                format = args[i].ToLowerInvariant();
                if (!OutputFormat.All.Contains(format))
                    return (null, $"Option '{arg}' must be one of: {string.Join(", ", OutputFormat.All)}.");
            }
            else if (!positionalOnly && arg == "--segments")
            {
                segments = true;
            }
            else if (!positionalOnly && arg == "--list-languages")
            {
                listLanguages = true;
            }
            else if (!positionalOnly && arg == "--proxy")
            {
                if (++i >= args.Length) return (null, $"Option '{arg}' requires a value.");
                if (!Uri.TryCreate(args[i], UriKind.Absolute, out proxy)
                    || proxy.Scheme is not ("http" or "https" or "socks4" or "socks4a" or "socks5"))
                    return (null, $"Option '{arg}' requires an http, https, socks4, socks4a or socks5 URL.");
            }
            else if (!positionalOnly && arg == "--timeout")
            {
                if (++i >= args.Length) return (null, $"Option '{arg}' requires a value.");
                if (!double.TryParse(args[i], System.Globalization.NumberStyles.Float,
                        System.Globalization.CultureInfo.InvariantCulture, out var seconds)
                    || !double.IsFinite(seconds) || seconds <= 0 || seconds > int.MaxValue / 1000)
                    return (null, $"Option '{arg}' requires a positive number of seconds.");
                timeout = TimeSpan.FromSeconds(seconds);
            }
            else if (!positionalOnly && arg.StartsWith('-'))
            {
                return (null, $"Unknown option '{arg}'.");
            }
            else if (url == null)
            {
                url = arg;
            }
            else
            {
                return (null, "Only one YouTube URL or video ID can be specified.");
            }
        }

        if (showHelp && showVersion)
            return (null, "Options '--help' and '--version' cannot be used together.");
        if (format != OutputFormat.Json && (metadataOnly || segments))
            return (null, $"Option '--format {format}' writes only the transcript, so it cannot be used with '{(metadataOnly ? "--metadata-only" : "--segments")}'.");
        if (listLanguages && (metadataOnly || segments || format != OutputFormat.Json))
            return (null, "Option '--list-languages' cannot be used with '--metadata-only', '--segments' or '--format'.");

        return (new Options(url, language, metadataOnly, compact, showHelp, showVersion, languageSpecified, timeout,
            format, segments, listLanguages, proxy), null);
    }

    internal static string GetVersion()
    {
        var informationalVersion = typeof(Program).Assembly
            .GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
        return informationalVersion?.Split('+')[0]
            ?? typeof(Program).Assembly.GetName().Version?.ToString(3)
            ?? "unknown";
    }

    // Best language match first, then human-written over auto-generated. With no match,
    // English is still preferred so an unknown -l keeps the pre-1.0.9 fallback.
    internal static ClosedCaptionTrackInfo? SelectTrack(IEnumerable<ClosedCaptionTrackInfo> tracks, string preference) =>
        tracks
            .OrderByDescending(t => LanguageMatchRank(t.Language.Code, t.Language.Name, preference))
            .ThenByDescending(t => LanguageMatchRank(t.Language.Code, t.Language.Name, "en"))
            .ThenBy(t => t.IsAutoGenerated)
            .FirstOrDefault();

    internal static bool LanguageMatches(string code, string name, string preference) =>
        LanguageMatchRank(code, name, preference) > 0;

    // 4 exact code, 3 exact name, 2 code prefix ("en" matches "en-GB"), 1 name substring, 0 none.
    // Substring needs more than 3 characters: "fr" is inside "Afrikaans" and "en" inside "French".
    internal static int LanguageMatchRank(string code, string name, string preference)
    {
        if (code.Equals(preference, StringComparison.OrdinalIgnoreCase)) return 4;
        if (name.Equals(preference, StringComparison.OrdinalIgnoreCase)) return 3;
        if (code.Length > preference.Length && code[preference.Length] == '-'
            && code.StartsWith(preference, StringComparison.OrdinalIgnoreCase)) return 2;
        if (preference.Length > 3 && name.Contains(preference, StringComparison.OrdinalIgnoreCase)) return 1;
        return 0;
    }

    internal static string ToHhMmSs(TimeSpan ts) => AppendTimestamp(new StringBuilder(), ts).ToString();

    private static StringBuilder AppendTimestamp(StringBuilder sb, TimeSpan ts)
    {
        int h = (int)ts.TotalHours;
        return h > 0
            ? sb.Append($"{h:00}:{ts.Minutes:00}:{ts.Seconds:00}")
            : sb.Append($"{ts.Minutes:00}:{ts.Seconds:00}");
    }

    [GeneratedRegex(@"\s+")]
    private static partial Regex WhitespaceRun();

    internal static string NormalizeCaption(string text)
    {
        if (string.IsNullOrWhiteSpace(text)) return "";
        // Replace entities first so "a&nbsp;&nbsp;b" collapses to one space like any other run.
        if (text.Contains("&nbsp;")) text = text.Replace("&nbsp;", " ");
        // \s+ also matches every single space, so the regex would allocate a new string
        // for nearly every caption. Only run it when the text is not already normalized.
        return NeedsWhitespaceNormalizing(text) ? WhitespaceRun().Replace(text, " ").Trim() : text;
    }

    // True when the text has leading or trailing whitespace, a run of spaces, or any
    // whitespace other than a plain space. char.IsWhiteSpace and the regex \s match the same set.
    private static bool NeedsWhitespaceNormalizing(ReadOnlySpan<char> text)
    {
        if (char.IsWhiteSpace(text[0]) || char.IsWhiteSpace(text[^1])) return true;
        for (var i = 1; i < text.Length; i++)
        {
            var c = text[i];
            if (c == ' ' ? text[i - 1] == ' ' : char.IsWhiteSpace(c)) return true;
        }
        return false;
    }
}
