using System.Reflection;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using YoutubeExplode;
using YoutubeExplode.Videos;
using YoutubeExplode.Videos.ClosedCaptions;

record Input(string url);

record Options(
    string? Url,
    string Language,
    bool MetadataOnly,
    bool Compact,
    bool ShowHelp,
    bool ShowVersion);

class Output
{
    public string url { get; set; } = "";
    public string title { get; set; } = "";
    public string description { get; set; } = "";
    public string transcriptRaw { get; set; } = "";
    public string transcript { get; set; } = "";
}

// Source-generated metadata skips reflection setup at startup and keeps JSON
// working under trimming and NativeAOT, where reflection-based serialization is disabled.
[JsonSerializable(typeof(Input))]
[JsonSerializable(typeof(Output))]
partial class YtxJsonContext : JsonSerializerContext
{
}

static partial class Program
{
    private const string Usage = """
        ytx extracts YouTube video metadata and captions as JSON.

        Usage:
          ytx [options] <URL_OR_VIDEO_ID>
          echo '{"url":"URL_OR_VIDEO_ID"}' | ytx [options]

        Arguments:
          URL_OR_VIDEO_ID           A YouTube URL or video ID.

        Options:
          -u, --url <value>         Specify the YouTube URL or video ID explicitly.
          -l, --language <value>    Prefer captions matching a language name or code
                                    (default: English).
              --metadata-only       Skip caption retrieval and return metadata only.
          -c, --compact             Write compact JSON instead of indented JSON.
          -h, -?, --help            Show help and exit.
          -v, --version             Show version and exit.

        Output:
          JSON is written to stdout. Diagnostics are written to stderr.

        Exit codes:
          0  Success
          1  Video retrieval or another runtime error
          2  Invalid command-line usage or input
        """;

    static async Task<int> Main(string[] args)
    {
        var (options, error) = ParseOptions(args);
        if (error != null)
        {
            Console.Error.WriteLine($"Error: {error}");
            Console.Error.WriteLine("Try 'ytx --help' for more information.");
            return 2;
        }

        if (options!.ShowHelp)
        {
            Console.WriteLine(Usage);
            return 0;
        }

        if (options.ShowVersion)
        {
            Console.WriteLine($"ytx {GetVersion()}");
            return 0;
        }

        string? url = options.Url;
        if (url == null && Console.IsInputRedirected)
        {
            var stdin = await Console.In.ReadToEndAsync();
            if (!string.IsNullOrWhiteSpace(stdin))
            {
                try
                {
                    var input = JsonSerializer.Deserialize(stdin.Trim(),
                        new YtxJsonContext(new JsonSerializerOptions { PropertyNameCaseInsensitive = true }).Input);
                    url = input?.url;
                }
                catch (JsonException ex)
                {
                    Console.Error.WriteLine($"Error: Invalid JSON input: {ex.Message}");
                    return 2;
                }
            }
        }

        if (string.IsNullOrWhiteSpace(url))
        {
            Console.Error.WriteLine("Error: A YouTube URL or video ID is required.");
            Console.Error.WriteLine("Try 'ytx --help' for more information.");
            return 2;
        }

        var videoId = VideoId.TryParse(url);
        if (videoId == null)
        {
            Console.Error.WriteLine($"Error: '{url}' is not a valid YouTube URL or video ID.");
            return 2;
        }

        try
        {
            var client = new YoutubeClient();
            var video = await client.Videos.GetAsync(videoId.Value);
            var title = video.Title ?? "";
            var description = video.Description ?? "";

            string transcriptRaw = "";
            string transcriptMd = options.MetadataOnly ? "_Caption retrieval skipped._" : "";

            if (!options.MetadataOnly)
            {
                try
                {
                    var manifest = await client.Videos.ClosedCaptions.GetManifestAsync(video.Id);
                    var track = manifest.Tracks
                        .OrderByDescending(t => LanguageMatches(t.Language.Code, t.Language.Name, options.Language))
                        .ThenByDescending(t => t.IsAutoGenerated)
                        .FirstOrDefault();

                    if (track != null)
                    {
                        var captions = await client.Videos.ClosedCaptions.GetAsync(track);
                        (transcriptRaw, transcriptMd) = BuildTranscript(video.Id.Value, captions.Captions);
                    }
                    else
                    {
                        transcriptMd = "_No transcript/captions available for this video._";
                    }
                }
                catch
                {
                    transcriptMd = "_No transcript/captions available or captions retrieval failed._";
                }
            }

            var output = new Output
            {
                url = url,
                title = title,
                description = description,
                transcriptRaw = transcriptRaw,
                transcript = transcriptMd
            };

            Console.OutputEncoding = Encoding.UTF8;
            using (var stdout = Console.OpenStandardOutput())
            {
                WriteOutput(stdout, output, options.Compact);
            }
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
            return 1;
        }
    }

    internal static (string Raw, string Markdown) BuildTranscript(string videoId, IEnumerable<ClosedCaption> captions)
    {
        var rawSb = new StringBuilder();
        var mdSb = new StringBuilder();

        foreach (var caption in captions)
        {
            var text = NormalizeCaption(caption.Text);
            if (string.IsNullOrWhiteSpace(text)) continue;

            if (rawSb.Length > 0)
            {
                rawSb.Append(' ');
                mdSb.Append(Environment.NewLine);
            }
            rawSb.Append(text);

            // Appending interpolated strings to a StringBuilder formats in place, with no temporary strings.
            mdSb.Append("- [");
            AppendTimestamp(mdSb, caption.Offset);
            mdSb.Append($"](https://www.youtube.com/watch?v={videoId}&t={(int)caption.Offset.TotalSeconds}s) ");
            mdSb.Append(text);
        }

        return (rawSb.ToString().Trim(), mdSb.ToString().TrimEnd());
    }

    // Writes UTF-8 without a BOM and ends with the platform newline, matching Console.WriteLine.
    internal static void WriteOutput(Stream stream, Output output, bool compact)
    {
        var context = new YtxJsonContext(new JsonSerializerOptions
        {
            WriteIndented = !compact,
            Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
        });

        // Serializing to a string sizes its buffer for the worst-case escape of the whole
        // transcript and then copies it as UTF-16. Writing UTF-8 to the stream avoids both.
        JsonSerializer.Serialize(stream, output, context.Output);
        stream.Write(Encoding.UTF8.GetBytes(Environment.NewLine));
        stream.Flush();
    }

    internal static (Options? Options, string? Error) ParseOptions(string[] args)
    {
        string? url = null;
        var language = "English";
        var metadataOnly = false;
        var compact = false;
        var showHelp = false;
        var showVersion = false;
        var positionalOnly = false;

        for (var i = 0; i < args.Length; i++)
        {
            var arg = args[i];
            if (!positionalOnly && arg == "--")
            {
                positionalOnly = true;
            }
            else if (!positionalOnly && arg is "-h" or "-?" or "--help")
            {
                showHelp = true;
            }
            else if (!positionalOnly && arg is "-v" or "--version")
            {
                showVersion = true;
            }
            else if (!positionalOnly && arg is "-c" or "--compact")
            {
                compact = true;
            }
            else if (!positionalOnly && arg == "--metadata-only")
            {
                metadataOnly = true;
            }
            else if (!positionalOnly && arg is "-u" or "--url")
            {
                if (++i >= args.Length) return (null, $"Option '{arg}' requires a value.");
                if (url != null) return (null, "The YouTube URL or video ID can only be specified once.");
                url = args[i];
            }
            else if (!positionalOnly && arg is "-l" or "--language")
            {
                if (++i >= args.Length || string.IsNullOrWhiteSpace(args[i]))
                    return (null, $"Option '{arg}' requires a value.");
                language = args[i];
            }
            else if (!positionalOnly && arg.StartsWith('-'))
            {
                return (null, $"Unknown option '{arg}'.");
            }
            else if (url == null)
            {
                url = arg;
            }
            else
            {
                return (null, "Only one YouTube URL or video ID can be specified.");
            }
        }

        if (showHelp && showVersion)
            return (null, "Options '--help' and '--version' cannot be used together.");

        return (new Options(url, language, metadataOnly, compact, showHelp, showVersion), null);
    }

    internal static string GetVersion()
    {
        var informationalVersion = typeof(Program).Assembly
            .GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
        return informationalVersion?.Split('+')[0]
            ?? typeof(Program).Assembly.GetName().Version?.ToString(3)
            ?? "unknown";
    }

    internal static bool LanguageMatches(string code, string name, string preference) =>
        code.Equals(preference, StringComparison.OrdinalIgnoreCase)
        || name.Equals(preference, StringComparison.OrdinalIgnoreCase)
        || name.Contains(preference, StringComparison.OrdinalIgnoreCase);

    internal static string ToHhMmSs(TimeSpan ts) => AppendTimestamp(new StringBuilder(), ts).ToString();

    private static StringBuilder AppendTimestamp(StringBuilder sb, TimeSpan ts)
    {
        int h = (int)ts.TotalHours;
        return h > 0
            ? sb.Append($"{h:00}:{ts.Minutes:00}:{ts.Seconds:00}")
            : sb.Append($"{ts.Minutes:00}:{ts.Seconds:00}");
    }

    [GeneratedRegex(@"\s+")]
    private static partial Regex WhitespaceRun();

    internal static string NormalizeCaption(string text)
    {
        if (string.IsNullOrWhiteSpace(text)) return "";
        // \s+ also matches every single space, so the regex would allocate a new string
        // for nearly every caption. Only run it when the text is not already normalized.
        if (NeedsWhitespaceNormalizing(text)) text = WhitespaceRun().Replace(text, " ").Trim();
        return text.Contains("&nbsp;") ? text.Replace("&nbsp;", " ") : text;
    }

    // True when the text has leading or trailing whitespace, a run of spaces, or any
    // whitespace other than a plain space. char.IsWhiteSpace and the regex \s match the same set.
    private static bool NeedsWhitespaceNormalizing(ReadOnlySpan<char> text)
    {
        if (char.IsWhiteSpace(text[0]) || char.IsWhiteSpace(text[^1])) return true;
        for (var i = 1; i < text.Length; i++)
        {
            var c = text[i];
            if (c == ' ' ? text[i - 1] == ' ' : char.IsWhiteSpace(c)) return true;
        }
        return false;
    }
}
